---
id: Db
name: Db
full: Database abstraction library
description: Database access and SQL abstraction layer.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Db
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Mike Naberezny
    user: mnaberez
    email: mike@naberezny.com
    active: false
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha4
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^7.4 || ^8
    composer:
      horde/date: ^3
      horde/exception: ^3
      horde/support: ^3
      horde/util: ^3
  optional:
    composer:
      horde/autoloader: ^3
      horde/cache: ^3
      horde/log: ^3
    ext:
      mysql: '*'
      mysqli: '*'
      oci8: '*'
      PDO: '*'
  dev:
    composer:
      horde/test: ^3
      horde/autoloader: ^3
      horde/cache: ^3
      horde/log: ^3
